name: CI

on: [push, release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/loom-cache
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: build/libs/*.jar